### PR TITLE
Refactor models and entities

### LINKED ISSUE #79: [B] Allow support for connection strings
Refactor the Connection model and entities to allow for either a connection string or manual specification

### PR DESCRIPTION
**Pull request by adityavidyadharan**
# ‼️ Needs `UserDate.sqlite3` to be deleted
The modification to `ConnectionEntity` means that old instances of the local DB won't work, so it needs to be deleted for your local to work.

# Description

Refactors the Connection model/entities to allow for a connection string or manual specification to be used

## Link to the issue you are closing

Fixes #79 

```ts
{
Created manual ConnectionModel {
  id: 1,
  nickname: 'manual',
  type: 'PostgreSQL',
  connectionConfig: {
    config: 'manual',
    address: 'asdf',
    port: 123,
    password: 'test',
    username: 'asdf'
  }
}
Created connection string ConnectionModel {
  id: 2,
  nickname: 'CS',
  type: 'PostgreSQL',
  connectionConfig: { config: 'string', connectionString: 'connectstring' }
}
Created entries:
[
  ConnectionModel {
    nickname: 'manual',
    id: 1,
    createdDate: 2022-09-27T03:28:46.000Z,
    lastUsed: 2022-09-27T03:28:46.740Z,
    type: 'PostgreSQL',
    connectionConfig: {
      config: 'manual',
      username: 'asdf',
      password: 'test',
      address: 'asdf',
      port: 123
    }
  },
  ConnectionModel {
    nickname: 'CS',
    id: 2,
    createdDate: 2022-09-27T03:28:46.000Z,
    lastUsed: 2022-09-27T03:28:46.791Z,
    type: 'PostgreSQL',
    connectionConfig: { config: 'string', connectionString: 'connectstring' }
  }
]
```

# Checklist:

- [x] ESLint passes
- [x] Prettier passes
- [x] Included comments where necessary
- [x] Updated README if needed
- [x] Verified that code runs and generates no errors/warnings

### CODE REVIEW

**Comment by insaan21** [comment]
Is the idea that if the config is a string this connection string will allow us to connect to the DB? If so, should we change Procedures.ts to check for this as well

**Comment by adityavidyadharan** [comment]
> Is the idea that if the config is a string this connection string will allow us to connect to the DB? If so, should we change Procedures.ts to check for this as well

Do you mean when we instantiate the `Pool`? That's done in `PgClient.ts` and I updated that logic
```ts
if (model.connectionConfig.config === 'manual') {
      this.pool = new Pool({
        host: model.connectionConfig.address,
        port: model.connectionConfig.port,
        password: model.connectionConfig.password,
        user: model.connectionConfig.username,
        database: 'React',
      });
    } else {
      this.pool = new Pool({
        connectionString: model.connectionConfig.connectionString,
      });
    }
```

**Review by insaan21 — APPROVED** [review]
Bet

**Review by JackFratto — APPROVED** [review]
Awesome sauce

**Pull request merged**
